name: environment_service
description: A simple service to store the active app environment
version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  rxdart: ^0.19.0

dev_dependencies:
  test: ^1.0.0
